/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-108651-gd2fd0ea1d7-20221015"
#endif /* AVUTIL_FFVERSION_H */
